org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.234
neo_version_range=[21.1,)
loader_version_range=[4,)

mod_id=lightspeed
mod_name=Lightspeed
mod_license=All Rights Reserved
mod_version=1.21.1-1.2.1
mod_group_id=com.ccr4ft3r
mod_authors=CCr4ft3r,kltyton
mod_description=Buys you time by loading heavy modpacks significantly faster.
